### ISSUE TITLE
Can jQuery-touch-events work with Framework7?

### ISSUE THREAD

**Issue by LarsVoith** [benmajor/jQuery-Touch-Events#113]
Framework7 seems to be lacking touch events maybe jQuery-touch-events could it be made compatible with it? 

Framework 7 does have the same syntax as jQuery library with some minor difference.
[https://framework7.io](url)
[https://github.com/nolimits4web/Framework7](url)

Thoughts?

**Comment by benmajor** [comment]
Hi Lars,

Yes, the framework can be combined for use with Framework7. However, the events from jQuery-touch-events won't work with F7's own selector engine (`$$`), since it does not return jQuery objects. You'll obviously need to include jQuery and use jQuery / Sizzle to select elements and handle events. 

You can also combine F7 events with those provided by this library, for example:

**Framework7 Events:**
```
$$('.some-link').on('taphold', function () {
  myApp.alert('Tap hold fired!');
});
```

**jQuery-touch-events:**
```
$('.some-link').on('taphold', function() {
  myApp.alert('Tap hold fired!');
});
```

**Comment by LarsVoith** [comment]
Great! thanks
