### ISSUE TITLE
Suggestion:  event mirroring strategy

### ISSUE THREAD

**Issue by ChronicLogic** [benmajor/jQuery-Touch-Events#130]
I have found that the behavior is not ideal for touch-capable laptops, although I admit I could be mistaken.  If I am, please inform me.

The idea of having a library that abstracts the 'applicable/compatible' events to simplify development when the targets are many is appealing.  However, the current approach, from code at 1.0.8 is thus:

            startevent:  (touchCapable) ? 'touchstart' : 'mousedown',
            endevent:    (touchCapable) ? 'touchend' : 'mouseup',
            moveevent:   (touchCapable) ? 'touchmove' : 'mousemove',
            tapevent:    (touchCapable) ? 'tap' : 'click',
            scrollevent: (touchCapable) ? 'touchmove' : 'scroll',

I believe this results in a problem on a touch-capable laptop.  I own such a laptop.  I could touch the screen if I wanted, but I don't often.  Half the time I'm connected to it via a terminal session and I could not touch even if I wanted to.  However, I believe Chrome probably currently reports that the page is "touchCapable'.  This means that the events do not fall back to desktop versions when I work over terminal session yet I absolutely can't touch in that case.  In your prior version I didn't have this problem (when you looked at user agent) but that solution had issues also, I understand the need for the change.  You should by the way remove the comment about the isChromeDesktop variable that no longer applies.  I believe that currently because the laptop is "touch capable" then click basically stops working, and it shouldn't.  I had thought the point of this library was to avoid making twice the event hookups.  As I said, most of the time I don't touch, and the rest of the time I can't touch, although it IS capable at the hardware.  You probably didn't intend that the prior code would work, but it did, and I never knew that the library didn't do what I thought it should do.

Regardless of intent, the current code seems to create an "either touch or click" scenario.  As if a device would exclusively support one or the other, but that's not how reality is.

I would suggest a different approach that I think would work better:  always support both events, treat them like they are interchangeable, make sure to only fire one or the other, not both.  So on my laptop when I am in a direct session (not a terminal, I'm sitting in front of the screen) I could touch OR click any time and it would fire the ONE related event handler for EITHER event, because both would be active (but only one event instance would fire if I touch OR click).  When I'm in terminal session and touch may be "capable" but yet impossible, click events will work fine.  When I'm live and touch is possible yet not preferred, click events will work fine.  Of course on a phone or tablet that is generally touch only for 99% of uses, touch would work, and on a desktop with no touch screen, click would work.  Currently the code seems to be missing the case where a device supports BOTH at once.  I don't know if this would be a big change or a little one.  It seems potentially small, if the abstractions are already where needed.  Thoughts?

**Comment by benmajor** [comment]
Thanks for your message. This has been something I've been thinking about for a couple of months actually, but I think it's outside of the scope of the project. The original concept for the library was to tackle basic website handling of events for mobile, tablet and desktop. At the time it was originally authored, touch-enabled notebooks and laptops were not prevalent, and so little regard was made to devices which have both pointer and touch events. It was designed to act as a simple DOM event library, as you say, for *either* touch or click.

For now, I will not be implementing both events into this library, because in my opinion it will dilute the original intention of this, and I don't see much point. If you need to handle both event types, you can do it quite easily using:

`$('ele').on('mousedown,touchstart', function() {  })`

And this would negate the purpose of some of the more intricate parts of the lib. 

I appreciate your input, but for now the focus remains on keeping the simplicity and allowing one event to be handled correctly primarily on **mobile** and **pointer** devices.
