### ISSUE TITLE
possibility to set threshold (or any other settings) globally

### ISSUE THREAD

**Issue by russ666** [benmajor/jQuery-Touch-Events#134]
it could be a good feature to set any settings globally once

**Comment by benmajor** [comment]
Yes, this is a good suggestion, and something I will add to 2.0.

**Comment by benmajor** [comment]
This is now fixed with v2.0.0. You can access the setters using the new `$.touch` namespace. The following setters are supported:

Set the X threshold for swipe events:
`$.touch.setSwipeThresholdX(threshold);`

Set the Y threshold of swipe events:
`$.touch.setSwipeThresholdY(threshold)`

Set the double tap interval:
`$.touch.setDoubleTapInt(interval);`

Set the taphold threshold:
`$.touch.setTapHoldThreshold(threshold);`

Set the pixel range for tapas:
`$.touch.setTapRange(ranger);`
