### ISSUE TITLE
desktop is ok but there are some problems on mobile

### ISSUE THREAD

**Issue by peratik** [benmajor/jQuery-Touch-Events#142]
Hello

Please visit http://peratik.com/ws/ on desktop, working great with mouse, but on mobile there are some problems:

1. touchmove not catching cells.
2. touchmove from top to bottom cause browser pull to refresh.

Please advice.

Thank you

**Comment by imbrish** [comment]
1. Are you sure it is not some error on your part? Doesn't work either when using "device mode" in Chrome debug console.
2. I don't think there is much that can or should be done about that. When dragging beyond start of the page mobile will assume that you want to refresh and we shouldn't mess with that, because it is mostly desirable. However you can take a look at https://stackoverflow.com/q/29008194/2646927 and https://docs.google.com/document/d/12Ay4s3NWake8Qd6xQeGiYimGJ_gCe0UMDZKwP9Ni4m8/mobilebasic if you want to disable this in your app.

**Comment by benmajor** [comment]
Yes, I agree with @imbrish; it seems the first one is an application error in your code (without a minimised example replicating the issue, it's difficult to say).

2. There's nothing the library can do about that unfortunately, unless you wish to wrap it using Cordova or something similar.
