### ISSUE TITLE
Tapend not invoke on tap move out of screen

### ISSUE THREAD

**Issue by acarli82** [benmajor/jQuery-Touch-Events#75]
Hi,
if i tap on screen tap start event is call, but if i move finger out of browser screen the tap end event is not call.

**Comment by benmajor** [comment]
Hello,

This is because there is no way for JS to fire an event when a user's finger leaves the screen (because it does not have access outside of the browser). This won't be fixed in the library. You will need to implement some kind of solution (probably using `setTimeout` or similar.

Regards,
Ben.
